@startuml
class Member{
}

class BoardMember {
}

class Event {
}

class Conference {
}

class BoardMeeting {
}

class Location {
}

class Person {
}

class AAUOC {
}

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- "0..*" Event
AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Location

Location "1" -- "0..*" Event : isLocated In
Event "0..*" -- "0..*" Member : attendsTo
BoardMeeting "0..*" -- "0..*" BoardMember : attendsTo
Conference "0..*" -- "0..*" Person : attendsTo

@enduml